baseURL = 'https://pcf.community/'
languageCode = 'en-us'
title = 'Programming Contest Foundation'
theme = "terminal"
publishDir = "docs/"

[params]
    themeColor = "green"
    showMenuItems  = 2
    centerTheme = true
